const cfg=window.APP_CONFIG||{};const sb=window.supabase?.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);const $=id=>document.getElementById(id);let businesses=[];let editing=null;let mediaKind='image';let mediaItems=[];
function sanitizeRichHTML(html){const doc=new DOMParser().parseFromString(String(html||''),'text/html');const allowed=new Set(['P','BR','STRONG','B','EM','I','U','H2','H3','UL','OL','LI','BLOCKQUOTE','A']);doc.body.querySelectorAll('*').forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(...Array.from(el.childNodes));return}Array.from(el.attributes).forEach(a=>{if(el.tagName==='A' && a.name==='href' && /^https?:\/\//i.test(a.value)){el.setAttribute('target','_blank');el.setAttribute('rel','noopener noreferrer')}else el.removeAttribute(a.name)})});return doc.body.innerHTML}
function initRichEditor(){const ed=$('descriptionEditor');if(!ed)return;document.querySelectorAll('.rich-toolbar button').forEach(btn=>btn.addEventListener('click',()=>{ed.focus();document.execCommand(btn.dataset.cmd,false,btn.dataset.value||null)}))}
function setRichHTML(html){if($('descriptionEditor'))$('descriptionEditor').innerHTML=sanitizeRichHTML(html||'')}
function getRichHTML(){const html=sanitizeRichHTML($('descriptionEditor')?.innerHTML||'');if($('description'))$('description').value=html;return html}
async function init(){if(!sb){$('loginMsg').textContent='Supabase no está configurado.';return}const {data:{session}}=await sb.auth.getSession();if(session)await dashboard();else $('logoutBtn').classList.add('hidden')}
async function login(e){e.preventDefault();$('loginMsg').textContent='Entrando…';const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)$('loginMsg').textContent=error.message;else await dashboard()}
async function dashboard(){const {data:{user}}=await sb.auth.getUser();const {data:p}=await sb.from('profiles').select('role').eq('id',user.id).single();if(p?.role==='admin'){location.href='../admin/';return}const {data:links,error:le}=await sb.from('business_users').select('business_id').eq('user_id',user.id);if(le){$('loginMsg').textContent=le.message;return}const ids=(links||[]).map(x=>x.business_id);$('loginPanel').classList.add('hidden');$('dashboard').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');if(!ids.length){$('list').innerHTML='<p>Tu cuenta está creada, pero todavía no tienes ningún establecimiento asignado. Contacta con el administrador.</p>';return}const {data,error}=await sb.from('businesses').select('*').in('id',ids).order('name');if(error){$('loginMsg').textContent=error.message;return}businesses=data||[];render()}
function render(){$('list').innerHTML=businesses.map(b=>`<div class="business-row"><div><strong>${esc(b.name)}</strong><div class="small">${esc(b.category||'')} · <span class="badge ${b.active?'on':''}">${b.active?'Activo':'Inactivo'}</span></div></div><button class="secondary" onclick="edit('${b.id}')">Editar</button></div>`).join('')}
window.edit=async id=>{const b=businesses.find(x=>x.id===id);if(!b)return;editing=b;for(const k of ['id','name','category','phone','whatsapp','website','instagram','address','offer','sponsor_name','sponsor_url'])if($(k))$(k).value=b[k]||'';setRichHTML(b.description||'');$('latitude').value=b.latitude??'';$('longitude').value=b.longitude??'';$('navigation_enabled').value=String(b.navigation_enabled!==false);$('target').value='';$('currentTarget').textContent=b.target_path?'Imagen actual: '+b.target_path:'Sin imagen';$('formMsg').textContent='';$('editor').classList.remove('hidden');$('mediaPanel').classList.remove('hidden');await loadMedia();window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
async function save(e){e.preventDefault();$('formMsg').textContent='Guardando…';const id=editing.id;let path=editing.target_path||'';const file=$('target').files[0];if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';path=`${id}.${ext}`;const {error:up}=await sb.storage.from('targets').upload(path,file,{upsert:true,contentType:file.type});if(up){$('formMsg').textContent='Error al subir imagen: '+up.message;return}}const payload={name:$('name').value.trim(),category:$('category').value.trim(),description:getRichHTML(),phone:$('phone').value.trim(),whatsapp:$('whatsapp').value.trim(),website:$('website').value.trim(),instagram:$('instagram').value.trim(),address:$('address').value.trim(),offer:$('offer').value.trim(),sponsor_name:$('sponsor_name').value.trim(),sponsor_url:$('sponsor_url').value.trim(),target_path:path,latitude:$('latitude').value?Number($('latitude').value):null,longitude:$('longitude').value?Number($('longitude').value):null,navigation_enabled:$('navigation_enabled').value==='true',updated_at:new Date().toISOString()};const {data,error}=await sb.from('businesses').update(payload).eq('id',id).select().single();if(error){$('formMsg').textContent=error.message;return}editing=data;businesses=businesses.map(x=>x.id===id?data:x);render();$('formMsg').textContent='Cambios guardados correctamente.'}
async function loadMedia(){if(!editing)return;const {data,error}=await sb.from('business_media').select('*').eq('business_id',editing.id).order('sort_order').order('created_at');if(error){$('mediaMsg').textContent=error.message;return}mediaItems=data||[];renderMedia()}
function renderMedia(){const items=mediaItems.filter(x=>x.media_type===mediaKind);if(!items.length){$('mediaList').innerHTML='<p class="small">Todavía no hay contenidos de este tipo.</p>';return}$('mediaList').innerHTML=items.map((m,i)=>{const url=publicMediaUrl(m);return `<div class="media-item"><div class="media-preview">${previewHtml(m,url)}</div><div class="media-meta"><strong>${esc(m.title||'Sin título')}</strong><p>${esc(m.description||'')}</p><span class="small">${m.active?'Publicado':'Oculto'} · ${esc(m.mime_type||'')}</span></div><div class="media-actions"><button type="button" class="secondary" onclick="moveMedia('${m.id}',-1)" ${i===0?'disabled':''}>↑</button><button type="button" class="secondary" onclick="moveMedia('${m.id}',1)" ${i===items.length-1?'disabled':''}>↓</button><button type="button" class="secondary" onclick="editMedia('${m.id}')">Editar</button><button type="button" class="secondary" onclick="toggleMedia('${m.id}')">${m.active?'Ocultar':'Publicar'}</button><button type="button" class="secondary" onclick="deleteMedia('${m.id}')">Eliminar</button></div></div>`}).join('')}
function publicMediaUrl(m){const bucket=m.media_type==='image'?'media-images':m.media_type==='audio'?'media-audio':'media-video';return sb.storage.from(bucket).getPublicUrl(m.storage_path).data.publicUrl}
function previewHtml(m,url){if(m.media_type==='image')return `<img src="${escAttr(url)}" alt="">`;if(m.media_type==='video')return `<video src="${escAttr(url)}" controls preload="metadata"></video>`;return `<audio src="${escAttr(url)}" controls preload="metadata"></audio>`}
function allowed(type,file){if(!file)return false;if(type==='image')return file.type.startsWith('image/');if(type==='audio')return file.type.startsWith('audio/');if(type==='video')return file.type.startsWith('video/');return false}
async function uploadMedia(){if(!editing)return;const file=$('mediaFile').files[0];if(!allowed(mediaKind,file)){$('mediaMsg').textContent='Selecciona un archivo válido para la pestaña actual.';return}if(file.size>50*1024*1024){$('mediaMsg').textContent='El archivo supera 50 MB. Para esta primera versión usamos un límite de 50 MB.';return}$('mediaMsg').textContent='Subiendo…';const bucket=mediaKind==='image'?'media-images':mediaKind==='audio'?'media-audio':'media-video';const ext=(file.name.split('.').pop()||'bin').toLowerCase().replace(/[^a-z0-9]/g,'')||'bin';const path=`${editing.id}__${crypto.randomUUID()}.${ext}`;const {error:up}=await sb.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(up){$('mediaMsg').textContent='Error al subir: '+up.message;return}const {error:dbErr}=await sb.from('business_media').insert({business_id:editing.id,media_type:mediaKind,storage_path:path,mime_type:file.type,title:$('mediaTitle').value.trim(),description:$('mediaDescription').value.trim(),sort_order:mediaItems.filter(x=>x.media_type===mediaKind).length});if(dbErr){await sb.storage.from(bucket).remove([path]);$('mediaMsg').textContent='El archivo se subió pero no se pudo registrar: '+dbErr.message;return}$('mediaFile').value='';$('mediaTitle').value='';$('mediaDescription').value='';$('mediaMsg').textContent='Contenido añadido correctamente.';await loadMedia()}
window.editMedia=async id=>{const m=mediaItems.find(x=>x.id===id);if(!m)return;const title=prompt('Título:',m.title||'');if(title===null)return;const description=prompt('Descripción:',m.description||'');if(description===null)return;const {error}=await sb.from('business_media').update({title,description,updated_at:new Date().toISOString()}).eq('id',id);$('mediaMsg').textContent=error?'Error: '+error.message:'Contenido actualizado.';await loadMedia()}
window.toggleMedia=async id=>{const m=mediaItems.find(x=>x.id===id);if(!m)return;const {error}=await sb.from('business_media').update({active:!m.active,updated_at:new Date().toISOString()}).eq('id',id);$('mediaMsg').textContent=error?'Error: '+error.message:(m.active?'Contenido ocultado.':'Contenido publicado.');await loadMedia()}
window.moveMedia=async(id,delta)=>{const items=mediaItems.filter(x=>x.media_type===mediaKind);const idx=items.findIndex(x=>x.id===id);const ni=idx+delta;if(idx<0||ni<0||ni>=items.length)return;const a=items[idx],b=items[ni];const {error:e1}=await sb.from('business_media').update({sort_order:b.sort_order,updated_at:new Date().toISOString()}).eq('id',a.id);if(e1){$('mediaMsg').textContent='Error al ordenar: '+e1.message;return}const {error:e2}=await sb.from('business_media').update({sort_order:a.sort_order,updated_at:new Date().toISOString()}).eq('id',b.id);if(e2){$('mediaMsg').textContent='Error al ordenar: '+e2.message;return}await loadMedia()}
window.deleteMedia=async id=>{const m=mediaItems.find(x=>x.id===id);if(!m||!confirm('¿Eliminar este contenido?'))return;const bucket=m.media_type==='image'?'media-images':m.media_type==='audio'?'media-audio':'media-video';const {error:re}=await sb.storage.from(bucket).remove([m.storage_path]);if(re){$('mediaMsg').textContent='No se pudo eliminar el archivo: '+re.message;return}const {error}=await sb.from('business_media').delete().eq('id',id);if(error){$('mediaMsg').textContent=error.message;return}$('mediaMsg').textContent='Contenido eliminado.';await loadMedia()}
async function logout(){await sb.auth.signOut();location.reload()}function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}function escAttr(s){return esc(s)}
initRichEditor();$('loginForm').addEventListener('submit',login);$('businessForm').addEventListener('submit',save);$('cancelBtn').addEventListener('click',()=>$('editor').classList.add('hidden'));$('uploadMediaBtn').addEventListener('click',uploadMedia);document.querySelectorAll('.media-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.media-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');mediaKind=btn.dataset.kind;const accept=mediaKind==='image'?'image/*':mediaKind==='audio'?'audio/*':'video/*';$('mediaFile').accept=accept;renderMedia()}));$('logoutBtn').addEventListener('click',logout);init();
