const cfg=window.APP_CONFIG||{};const sb=window.supabase?.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);const $=id=>document.getElementById(id);let editing=null;let me=null;let mediaKind='image';let mediaItems=[];let businesses=[];let collaborators=[];let collaboratorEditing=null;let routes=[];let routeEditing=null;let routeOrder=[];
function sanitizeRichHTML(html){const doc=new DOMParser().parseFromString(String(html||''),'text/html');const allowed=new Set(['P','BR','STRONG','B','EM','I','U','H2','H3','UL','OL','LI','BLOCKQUOTE','A']);doc.body.querySelectorAll('*').forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(...Array.from(el.childNodes));return}Array.from(el.attributes).forEach(a=>{if(el.tagName==='A' && a.name==='href' && /^https?:\/\//i.test(a.value)){el.setAttribute('target','_blank');el.setAttribute('rel','noopener noreferrer')}else el.removeAttribute(a.name)})});return doc.body.innerHTML}
function initRichEditor(){const ed=$('descriptionEditor');if(!ed)return;document.querySelectorAll('.rich-toolbar button').forEach(btn=>btn.addEventListener('click',()=>{ed.focus();const cmd=btn.dataset.cmd,val=btn.dataset.value;document.execCommand(cmd,false,val||null)}))}
function setRichHTML(html){if($('descriptionEditor'))$('descriptionEditor').innerHTML=sanitizeRichHTML(html||'')}
function getRichHTML(){const html=sanitizeRichHTML($('descriptionEditor')?.innerHTML||'');if($('description'))$('description').value=html;return html}
function configured(){return sb&&!cfg.SUPABASE_URL.includes('TU-PROYECTO')&&!cfg.SUPABASE_PUBLISHABLE_KEY.includes('TU_PUBLISHABLE')}
async function init(){if(!configured()){$('loginMsg').textContent='Primero configura config.js con la URL y Publishable Key de Supabase.';return}const {data:{session}}=await sb.auth.getSession();if(session)await showDashboard()}
async function login(e){e.preventDefault();setMsg('loginMsg','Entrando…');const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)setMsg('loginMsg',error.message);else await showDashboard()}
async function showDashboard(){const {data:user}=await sb.auth.getUser();me=user?.user;if(!me){location.reload();return}const {data:p,error}=await sb.from('profiles').select('*').eq('id',me.id).single();if(error||!p){$('loginMsg').textContent='Tu usuario no tiene perfil. Ejecuta el SQL de v8.5 en Supabase.';return}if(p.role!=='admin'){location.href='../owner/';return}$('loginPanel').classList.add('hidden');$('dashboard').classList.remove('hidden');await loadList();await loadOwners();$('collaboratorsPanel').classList.remove('hidden');await loadCollaborators();await loadRoutesAdmin()}
async function loadList(){const {data,error}=await sb.from('businesses').select('*').order('created_at',{ascending:false});if(error){$('list').innerHTML='<p>'+esc(error.message)+'</p>';return}businesses=data||[];$('list').innerHTML=(data||[]).map(b=>`<div class="business-row"><div><strong>${esc(b.name)}</strong><div class="small">${esc(b.category||'')} · <span class="badge ${b.active?'on':''}">${b.active?'Activo':'Inactivo'}</span></div></div><div><button class="secondary" onclick='editBusiness(${JSON.stringify(b).replace(/</g,"\\u003c")})'>Editar</button></div></div>`).join('')||'<p>No hay negocios todavía.</p>'}
async function loadOwners(){const {data:profiles,error}=await sb.from('profiles').select('*').order('email');if(error){$('ownersList').innerHTML='<p>'+esc(error.message)+'</p>';return}const {data:links}=await sb.from('business_users').select('business_id,user_id');const businesses=(await sb.from('businesses').select('id,name')).data||[];const map=new Map(businesses.map(b=>[b.id,b.name]));$('ownerSelect').innerHTML=(profiles||[]).filter(p=>p.role==='owner').map(p=>`<option value="${p.id}">${esc(p.email)}${p.full_name?' · '+esc(p.full_name):''}</option>`).join('')||'<option value="">No hay propietarios registrados</option>';$('ownerBusinessSelect').innerHTML=businesses.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('');$('ownersList').innerHTML=(profiles||[]).filter(p=>p.role==='owner').map(p=>{const mine=(links||[]).filter(x=>x.user_id===p.id).map(x=>map.get(x.business_id)).filter(Boolean);return `<div class="business-row"><div><strong>${esc(p.email)}</strong><div class="small">${mine.length?mine.map(esc).join(', '):'Sin negocios asignados'}</div></div></div>`}).join('')||'<p>No hay propietarios. Pídeles que se registren desde Acceso propietarios.</p>'}
function newBusiness(){editing=null;$('businessForm').reset();$('id').value='';$('editorTitle').textContent='Nuevo negocio';setRichHTML('');$('latitude').value='';$('longitude').value='';$('navigation_enabled').value='true';$('currentTarget').textContent='';$('formMsg').textContent='';$('editor').classList.remove('hidden');$('mediaPanel').classList.add('hidden')}
window.editBusiness=async b=>{editing=b;$('editorTitle').textContent='Editar negocio';for(const k of ['id','name','category','phone','whatsapp','website','instagram','address','offer','sponsor_name','sponsor_url'])if($(k))$(k).value=b[k]||'';setRichHTML(b.description||'');$('latitude').value=b.latitude??'';$('longitude').value=b.longitude??'';$('navigation_enabled').value=String(b.navigation_enabled!==false);$('active').value=String(!!b.active);$('target').value='';$('currentTarget').textContent=b.target_path?'Imagen actual: '+b.target_path:'Sin imagen';$('formMsg').textContent='';$('editor').classList.remove('hidden');$('mediaPanel').classList.remove('hidden');await loadMedia();window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
async function save(e){e.preventDefault();setMsg('formMsg','Guardando…');const id=$('id').value||crypto.randomUUID();let path=editing?.target_path||'';const file=$('target').files[0];if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';path=`${id}.${ext}`;const {error:up}=await sb.storage.from('targets').upload(path,file,{upsert:true,contentType:file.type});if(up){setMsg('formMsg','Error al subir imagen: '+up.message);return}}const payload={id,name:$('name').value.trim(),category:$('category').value.trim(),description:getRichHTML(),phone:$('phone').value.trim(),whatsapp:$('whatsapp').value.trim(),website:$('website').value.trim(),instagram:$('instagram').value.trim(),address:$('address').value.trim(),offer:$('offer').value.trim(),sponsor_name:$('sponsor_name').value.trim(),sponsor_url:$('sponsor_url').value.trim(),target_path:path,latitude:$('latitude').value?Number($('latitude').value):null,longitude:$('longitude').value?Number($('longitude').value):null,navigation_enabled:$('navigation_enabled').value==='true',active:$('active').value==='true',updated_at:new Date().toISOString()};const {error}=await sb.from('businesses').upsert(payload);if(error){setMsg('formMsg',error.message);return}editing={...(editing||{}),...payload};setMsg('formMsg','Guardado correctamente.');await loadList();setTimeout(()=>{$('editor').classList.add('hidden');$('mediaPanel').classList.add('hidden')},500)}
async function loadMedia(){if(!editing)return;const {data,error}=await sb.from('business_media').select('*').eq('business_id',editing.id).order('media_type').order('sort_order').order('created_at');if(error){$('mediaMsg').textContent='No se pudo cargar el contenido: '+error.message;return}mediaItems=data||[];renderMedia()}
function bucketFor(t){return t==='image'?'media-images':t==='audio'?'media-audio':'media-video'}
function publicMediaUrl(m){return sb.storage.from(bucketFor(m.media_type)).getPublicUrl(m.storage_path).data.publicUrl}
function previewHtml(m,url){if(m.media_type==='image')return `<img src="${escAttr(url)}" alt="">`;if(m.media_type==='video')return `<video src="${escAttr(url)}" controls preload="metadata"></video>`;return `<audio src="${escAttr(url)}" controls preload="metadata"></audio>`}
function renderMedia(){const items=mediaItems.filter(x=>x.media_type===mediaKind);if(!items.length){$('mediaList').innerHTML='<p class="small">Todavía no hay contenidos de este tipo.</p>';return}$('mediaList').innerHTML=items.map((m,i)=>{const url=publicMediaUrl(m);return `<div class="media-item"><div class="media-preview">${previewHtml(m,url)}</div><div class="media-meta"><strong>${esc(m.title||'Sin título')}</strong><p>${esc(m.description||'')}</p><span class="small">${m.active?'Publicado':'Oculto'} · ${esc(m.mime_type||'')}</span></div><div class="media-actions"><button type="button" class="secondary" onclick="moveMedia('${m.id}',-1)" ${i===0?'disabled':''}>↑</button><button type="button" class="secondary" onclick="moveMedia('${m.id}',1)" ${i===items.length-1?'disabled':''}>↓</button><button type="button" class="secondary" onclick="editMedia('${m.id}')">Editar</button><button type="button" class="secondary" onclick="toggleMedia('${m.id}')">${m.active?'Ocultar':'Publicar'}</button><button type="button" class="secondary" onclick="deleteMedia('${m.id}')">Eliminar</button></div></div>`}).join('')}
function allowed(type,file){return !!file&&((type==='image'&&file.type.startsWith('image/'))||(type==='audio'&&file.type.startsWith('audio/'))||(type==='video'&&file.type.startsWith('video/')))}
async function uploadMedia(){if(!editing)return;const file=$('mediaFile').files[0];if(!allowed(mediaKind,file)){setMsg('mediaMsg','Selecciona un archivo válido para la pestaña actual.');return}if(file.size>50*1024*1024){setMsg('mediaMsg','El archivo supera 50 MB.');return}setMsg('mediaMsg','Subiendo…');const bucket=bucketFor(mediaKind);const ext=(file.name.split('.').pop()||'bin').toLowerCase().replace(/[^a-z0-9]/g,'')||'bin';const path=`${editing.id}__${crypto.randomUUID()}.${ext}`;const {error:up}=await sb.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(up){setMsg('mediaMsg','Error al subir: '+up.message);return}const order=mediaItems.filter(x=>x.media_type===mediaKind).length;const {error:dbErr}=await sb.from('business_media').insert({business_id:editing.id,media_type:mediaKind,storage_path:path,mime_type:file.type,title:$('mediaTitle').value.trim(),description:$('mediaDescription').value.trim(),sort_order:order,active:true});if(dbErr){await sb.storage.from(bucket).remove([path]);setMsg('mediaMsg','No se pudo registrar: '+dbErr.message);return}$('mediaFile').value='';$('mediaTitle').value='';$('mediaDescription').value='';setMsg('mediaMsg','Contenido añadido correctamente.');await loadMedia()}
window.editMedia=async id=>{const m=mediaItems.find(x=>x.id===id);if(!m)return;const title=prompt('Título:',m.title||'');if(title===null)return;const description=prompt('Descripción:',m.description||'');if(description===null)return;const {error}=await sb.from('business_media').update({title,description,updated_at:new Date().toISOString()}).eq('id',id);setMsg('mediaMsg',error?'Error: '+error.message:'Contenido actualizado.');await loadMedia()}
window.toggleMedia=async id=>{const m=mediaItems.find(x=>x.id===id);if(!m)return;const {error}=await sb.from('business_media').update({active:!m.active,updated_at:new Date().toISOString()}).eq('id',id);setMsg('mediaMsg',error?'Error: '+error.message:(m.active?'Contenido ocultado.':'Contenido publicado.'));await loadMedia()}
window.moveMedia=async(id,delta)=>{const items=mediaItems.filter(x=>x.media_type===mediaKind);const idx=items.findIndex(x=>x.id===id);const ni=idx+delta;if(idx<0||ni<0||ni>=items.length)return;const a=items[idx],b=items[ni];const {error:e1}=await sb.from('business_media').update({sort_order:b.sort_order,updated_at:new Date().toISOString()}).eq('id',a.id);if(e1){setMsg('mediaMsg','Error al ordenar: '+e1.message);return}const {error:e2}=await sb.from('business_media').update({sort_order:a.sort_order,updated_at:new Date().toISOString()}).eq('id',b.id);if(e2){setMsg('mediaMsg','Error al ordenar: '+e2.message);return}await loadMedia()}
window.deleteMedia=async id=>{const m=mediaItems.find(x=>x.id===id);if(!m||!confirm('¿Eliminar este contenido?'))return;const {error:re}=await sb.storage.from(bucketFor(m.media_type)).remove([m.storage_path]);if(re){setMsg('mediaMsg','No se pudo eliminar el archivo: '+re.message);return}const {error}=await sb.from('business_media').delete().eq('id',id);setMsg('mediaMsg',error?error.message:'Contenido eliminado.');await loadMedia()}
async function loadCollaborators(){
  const {data,error}=await sb.from('tourism_collaborators').select('*').order('name');
  if(error){$('collaboratorsList').innerHTML='<p>'+esc(error.message)+'</p>';return}
  collaborators=data||[];
  renderCollaborators();
}
function renderCollaborators(){
  $('collaboratorsList').innerHTML=collaborators.map(c=>`<div class="business-row"><div><strong>${esc(c.name)}</strong><div class="small">${c.collaborator_type==='sponsor'?'Patrocinador':c.collaborator_type==='recommended'?'Establecimiento recomendado':'Colaborador'} · <span class="badge ${c.active?'on':''}">${c.active?'Publicado':'Oculto'}</span></div></div><button class="secondary" type="button" onclick="editCollaborator('${c.id}')">Editar</button></div>`).join('')||'<p>No hay colaboradores creados todavía.</p>';
}
function renderCollaboratorPlaces(selected=[]){
  const ids=new Set(selected.map(String));
  $('collaboratorPlaces').innerHTML=businesses.map(b=>`<label class="collaborator-place"><input type="checkbox" value="${escAttr(b.id)}" ${ids.has(String(b.id))?'checked':''}> <span><strong>${esc(b.name)}</strong><small>${esc(b.category||'')}</small></span></label>`).join('')||'<p class="small">Crea primero algún lugar o monumento.</p>';
}
function resetCollaboratorForm(){collaboratorEditing=null;$('collaboratorForm').reset();$('collaboratorId').value='';$('collaboratorEditorTitle').textContent='Nuevo colaborador';$('collaboratorActive').value='true';$('collaboratorType').value='collaborator';$('collaboratorRole').value='collaborator';$('collaboratorMsg').textContent='';renderCollaboratorPlaces([]);$('collaboratorEditor').classList.remove('hidden')}
window.editCollaborator=async id=>{const c=collaborators.find(x=>x.id===id);if(!c)return;collaboratorEditing=c;const {data}=await sb.from('tourism_collaborator_places').select('business_id,role').eq('collaborator_id',id);const rel=data||[];$('collaboratorId').value=c.id;$('collaboratorName').value=c.name||'';$('collaboratorType').value=c.collaborator_type||'collaborator';$('collaboratorDescription').value=c.description||'';$('collaboratorLogoUrl').value=c.logo_url||'';$('collaboratorWebsite').value=c.website||'';$('collaboratorPhone').value=c.phone||'';$('collaboratorWhatsapp').value=c.whatsapp||'';$('collaboratorInstagram').value=c.instagram||'';$('collaboratorActive').value=String(!!c.active);$('collaboratorRole').value=rel[0]?.role||c.collaborator_type||'collaborator';renderCollaboratorPlaces(rel.map(x=>x.business_id));$('collaboratorEditorTitle').textContent='Editar colaborador';$('collaboratorMsg').textContent='';$('collaboratorEditor').classList.remove('hidden')}
async function saveCollaborator(e){e.preventDefault();setMsg('collaboratorMsg','Guardando…');const id=$('collaboratorId').value||crypto.randomUUID();const payload={id,name:$('collaboratorName').value.trim(),collaborator_type:$('collaboratorType').value,description:$('collaboratorDescription').value.trim(),logo_url:$('collaboratorLogoUrl').value.trim(),website:$('collaboratorWebsite').value.trim(),phone:$('collaboratorPhone').value.trim(),whatsapp:$('collaboratorWhatsapp').value.trim(),instagram:$('collaboratorInstagram').value.trim(),active:$('collaboratorActive').value==='true',updated_at:new Date().toISOString()};const {error}=await sb.from('tourism_collaborators').upsert(payload);if(error){setMsg('collaboratorMsg','Error: '+error.message);return}const selected=[...document.querySelectorAll('#collaboratorPlaces input[type="checkbox"]:checked')].map(x=>x.value);const {error:delErr}=await sb.from('tourism_collaborator_places').delete().eq('collaborator_id',id);if(delErr){setMsg('collaboratorMsg','El colaborador se guardó, pero no se pudieron actualizar sus lugares: '+delErr.message);return}if(selected.length){const rows=selected.map((business_id,i)=>({collaborator_id:id,business_id,role:$('collaboratorRole').value,sort_order:i,active:payload.active}));const {error:relErr}=await sb.from('tourism_collaborator_places').insert(rows);if(relErr){setMsg('collaboratorMsg','El colaborador se guardó, pero falló la asociación: '+relErr.message);return}}setMsg('collaboratorMsg','Colaborador guardado correctamente.');await loadCollaborators();setTimeout(()=>resetCollaboratorForm(),400)}

async function loadRoutesAdmin(){
  const {data,error}=await sb.from('tourism_routes').select('*').order('name');
  if(error){$('routesAdminList').innerHTML='<p>'+esc(error.message)+'</p>';return}
  routes=data||[];
  $('routesAdminList').innerHTML=routes.map(r=>`<div class="business-row"><div><strong>${esc(r.name)}</strong><div class="small">${esc(r.category||'Ruta turística')} · <span class="badge ${r.active?'on':''}">${r.active?'Publicada':'Oculta'}</span></div></div><button class="secondary" type="button" onclick="editRoute('${r.id}')">Editar</button></div>`).join('')||'<p>No hay rutas creadas todavía.</p>';
}
function renderRoutePlaces(selected=[]){
  const ids=new Set(selected.map(String));
  const selectedBusinesses=businesses.filter(b=>ids.has(String(b.id)));
  const unselected=businesses.filter(b=>!ids.has(String(b.id)));
  routeOrder=[...selectedBusinesses.map(b=>b.id),...unselected.map(b=>b.id)];
  $('routePlaces').innerHTML=businesses.map(b=>`<label class="route-place-option"><input type="checkbox" data-route-place-check value="${escAttr(b.id)}" ${ids.has(String(b.id))?'checked':''}> <span><strong>${esc(b.name)}</strong><small>${esc(b.category||'')}</small></span></label>`).join('')||'<p class="small">Crea primero algún lugar o monumento.</p>';
  bindRoutePlaceChecks();
  refreshRouteOrderControls();
}
function bindRoutePlaceChecks(){document.querySelectorAll('[data-route-place-check]').forEach(x=>x.addEventListener('change',()=>{if(x.checked){if(!routeOrder.includes(x.value))routeOrder.push(x.value)}else{routeOrder=routeOrder.filter(id=>String(id)!==String(x.value))}refreshRouteOrderControls()}))}
function refreshRouteOrderControls(){
  const box=$('routePlaces'); if(!box)return;
  const checked=routeOrder.filter(id=>document.querySelector(`[data-route-place-check][value="${CSS.escape(String(id))}"]`)?.checked);
  const rows=checked.map((id,i)=>{const b=businesses.find(x=>String(x.id)===String(id));return b?`<div class="route-order-row"><div><strong>${esc(b.name)}</strong><small>${esc(b.category||'')}</small></div><div><button type="button" class="secondary route-order-btn" data-route-move="up" data-route-id="${escAttr(id)}" ${i===0?'disabled':''}>↑</button><button type="button" class="secondary route-order-btn" data-route-move="down" data-route-id="${escAttr(id)}" ${i===checked.length-1?'disabled':''}>↓</button></div></div>`:''}).join('');
  const checks=businesses.map(b=>`<label class="route-place-option"><input type="checkbox" data-route-place-check value="${escAttr(b.id)}" ${checked.includes(String(b.id))?'checked':''}> <span><strong>${esc(b.name)}</strong><small>${esc(b.category||'')}</small></span></label>`).join('');
  box.innerHTML=`<div class="route-selected-list">${rows||'<p class="small">No hay paradas seleccionadas todavía.</p>'}</div><div class="route-all-places"><div class="small"><strong>Añadir lugares</strong></div>${checks}</div>`;
  box.querySelectorAll('[data-route-place-check]').forEach(x=>x.addEventListener('change',()=>{if(x.checked&&!routeOrder.includes(x.value))routeOrder.push(x.value);if(!x.checked)routeOrder=routeOrder.filter(id=>String(id)!==String(x.value));refreshRouteOrderControls()}));
  box.querySelectorAll('[data-route-move]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.routeId;const ids=routeOrder.filter(x=>box.querySelector(`[data-route-place-check][value="${CSS.escape(String(x))}"]`)?.checked);const i=ids.indexOf(id);const ni=btn.dataset.routeMove==='up'?i-1:i+1;if(i<0||ni<0||ni>=ids.length)return;[ids[i],ids[ni]]=[ids[ni],ids[i]];const unchecked=routeOrder.filter(x=>!ids.includes(x));routeOrder=[...ids,...unchecked];refreshRouteOrderControls()}));
}
function resetRouteForm(){routeEditing=null;routeOrder=[];$('routeForm').reset();$('routeId').value='';$('routeEditorTitle').textContent='Nueva ruta';$('routeActive').value='true';$('routeMsg').textContent='';renderRoutePlaces([]);$('routeEditor').classList.remove('hidden')}
window.editRoute=async id=>{const r=routes.find(x=>String(x.id)===String(id));if(!r)return;routeEditing=r;const {data,error}=await sb.from('tourism_route_places').select('business_id,sort_order').eq('route_id',id).eq('active',true).order('sort_order');if(error){setMsg('routeMsg','No se pudieron cargar las paradas: '+error.message);return}const rel=data||[];routeOrder=rel.map(x=>x.business_id);$('routeId').value=r.id;$('routeName').value=r.name||'';$('routeCategory').value=r.category||'';$('routeDescription').value=r.description||'';$('routeCoverUrl').value=r.cover_url||'';$('routeDuration').value=r.duration_minutes??'';$('routeDistance').value=r.distance_meters??'';$('routeActive').value=String(!!r.active);$('routeEditorTitle').textContent='Editar ruta';$('routeMsg').textContent='';renderRoutePlaces(routeOrder);$('routeEditor').classList.remove('hidden');$('routeEditor').scrollIntoView({behavior:'smooth',block:'start'})}
async function saveRoute(e){e.preventDefault();setMsg('routeMsg','Guardando ruta…');const id=$('routeId').value||crypto.randomUUID();const payload={id,name:$('routeName').value.trim(),category:$('routeCategory').value.trim(),description:$('routeDescription').value.trim(),cover_url:$('routeCoverUrl').value.trim(),duration_minutes:$('routeDuration').value?Number($('routeDuration').value):null,distance_meters:$('routeDistance').value?Number($('routeDistance').value):null,active:$('routeActive').value==='true',updated_at:new Date().toISOString()};const {error}=await sb.from('tourism_routes').upsert(payload);if(error){setMsg('routeMsg','Error: '+error.message);return}const {error:del}=await sb.from('tourism_route_places').delete().eq('route_id',id);if(del){setMsg('routeMsg','La ruta se guardó, pero no se pudieron actualizar las paradas: '+del.message);return}const checked=routeOrder.filter(x=>document.querySelector(`[data-route-place-check][value="${CSS.escape(String(x))}"]`)?.checked);if(checked.length){const rows=checked.map((business_id,i)=>({route_id:id,business_id,sort_order:i,active:payload.active}));const {error:ins}=await sb.from('tourism_route_places').insert(rows);if(ins){setMsg('routeMsg','La ruta se guardó, pero falló el orden de las paradas: '+ins.message);return}}setMsg('routeMsg','Ruta guardada correctamente.');await loadRoutesAdmin();setTimeout(()=>{$('routeEditor').classList.add('hidden')},500)}
async function assignOwner(){const uid=$('ownerSelect').value,bid=$('ownerBusinessSelect').value;if(!uid||!bid){setMsg('ownerMsg','Selecciona propietario y negocio.');return}const {error}=await sb.from('business_users').upsert({user_id:uid,business_id:bid});setMsg('ownerMsg',error?'Error: '+error.message:'Permiso concedido correctamente.');await loadOwners()}
async function logout(){await sb.auth.signOut();location.reload()}function setMsg(id,m){$(id).textContent=m}function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}function escAttr(s){return esc(s)}
initRichEditor();$('newCollaboratorBtn').addEventListener('click',resetCollaboratorForm);$('newRouteBtn').addEventListener('click',resetRouteForm);$('cancelRouteBtn').addEventListener('click',()=>$('routeEditor').classList.add('hidden'));$('routeForm').addEventListener('submit',saveRoute);$('cancelCollaboratorBtn').addEventListener('click',()=>$('collaboratorEditor').classList.add('hidden'));$('collaboratorForm').addEventListener('submit',saveCollaborator);$('loginForm').addEventListener('submit',login);$('businessForm').addEventListener('submit',save);$('newBtn').addEventListener('click',newBusiness);$('cancelBtn').addEventListener('click',()=>$('editor').classList.add('hidden'));$('logoutBtn').addEventListener('click',logout);$('assignBtn').addEventListener('click',assignOwner);$('uploadMediaBtn').addEventListener('click',uploadMedia);document.querySelectorAll('.media-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.media-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');mediaKind=btn.dataset.kind;$('mediaFile').accept=mediaKind==='image'?'image/*':mediaKind==='audio'?'audio/*':'video/*';renderMedia()}));init();
